import html
import json
import os
import re
import subprocess
from pathlib import Path
from typing import Callable


MARKER_PREFIX = "<!-- poc-cli-review:"
FILE_BULLET = re.compile(
    r"^-\s+\*\*(Added|Modified|Deleted|Renamed)\*\*\s+`([^`]+)`\s+[—-]\s+(.+)$",
    re.MULTILINE,
)
STATUSES = {"A": "Added", "M": "Modified", "D": "Deleted", "R": "Renamed"}


def render_review(summary: str, name_status: str, head_sha: str) -> str:
    if not re.fullmatch(r"[0-9a-f]{40}", head_sha):
        raise ValueError("Invalid head SHA")
    if len(summary) > 30000 or MARKER_PREFIX in summary:
        raise ValueError("Invalid AI summary size or marker")
    headings = list(re.finditer(r"^## (Purpose|Changed files|Rule check)\s*$",
                               summary, re.MULTILINE))
    if [heading.group(1) for heading in headings] != [
        "Purpose", "Changed files", "Rule check"
    ]:
        raise ValueError("Missing AI summary sections")
    verdict = re.search(r"^Verdict: (PASS|FAIL)\s*$", summary, re.MULTILINE)
    if verdict is None or summary[verdict.end():].strip():
        raise ValueError("Invalid Verdict line")
    purpose = summary[headings[0].end():headings[1].start()].strip()
    files_text = summary[headings[1].end():headings[2].start()].strip()
    rules = summary[headings[2].end():verdict.start()].strip()
    if not purpose or not rules:
        raise ValueError("Missing purpose or rule check")

    descriptions = {}
    for match in FILE_BULLET.finditer(files_text):
        status, path, role = match.groups()
        if path in descriptions or not role.strip():
            raise ValueError(f"Duplicate or empty changed file: {path}")
        descriptions[path] = (status, role.strip())

    rows = []
    for entry in name_status.splitlines():
        parts = entry.split("\t")
        kind = parts[0][:1]
        if len(parts) < 2 or kind not in STATUSES:
            raise ValueError(f"Invalid changed-file entry: {entry}")
        path = parts[-1]
        if path not in descriptions:
            raise ValueError(f"AI summary missing changed file: {path}")
        status, role = descriptions.pop(path)
        if status != STATUSES[kind]:
            raise ValueError(f"Changed-file status mismatch: {path}")
        safe_path = html.escape(path).replace("|", r"\|")
        safe_role = html.escape(role).replace("|", r"\|")
        rows.append(f"| {status} | `{safe_path}` | {safe_role} |")
    if not rows or descriptions:
        raise ValueError("AI summary has missing or extra changed files")

    findings = re.findall(r"\[(?:STRUCT|CONTENT)-\d{2}\]", rules)
    status = verdict.group(1)
    if (status == "FAIL") != bool(findings):
        raise ValueError("Verdict disagrees with rule findings")
    heading = ("\U0001f7e1 Changes recommended — FAIL" if findings else
               "\U0001f7e2 No POC issues found — PASS")
    marker = f"{MARKER_PREFIX}{head_sha} -->"
    return (
        "## Copilot CLI review summary\n\n"
        f"### {heading}\n\n"
        f"{html.escape(purpose)}\n\n"
        "<details open>\n"
        f"<summary><strong>Rule check ({len(findings)})</strong></summary>\n\n"
        f"{rules}\n\n"
        "</details>\n\n"
        "<details>\n"
        f"<summary><strong>What changed in this PR ({len(rows)} files)</strong></summary>\n\n"
        "| Change | File | Purpose |\n"
        "|---|---|---|\n"
        + "\n".join(rows)
        + "\n\n</details>\n\n"
        "_Generated by a Copilot CLI custom agent; advisory, not an approval._\n\n"
        + marker
    )


def find_existing(reviews: list[dict], marker: str) -> int | None:
    for review in reviews:
        if (review.get("user") or {}).get("login") == "github-actions[bot]" \
                and marker in review.get("body", ""):
            return review["id"]
    return None


def publish_review(summary: str, name_status: str, repo: str, number: int,
                   head_sha: str,
                   request: Callable[[str, str, dict | None], object]) -> int:
    body = render_review(summary, name_status, head_sha)
    endpoint = f"repos/{repo}/pulls/{number}"
    current = request("GET", endpoint)
    if current["head"]["sha"] != head_sha:
        raise ValueError("PR head changed during review")
    reviews = request("GET", f"{endpoint}/reviews")
    existing = find_existing(reviews, f"{MARKER_PREFIX}{head_sha} -->")
    if existing is None:
        result = request("POST", f"{endpoint}/reviews",
                         {"body": body, "event": "COMMENT", "commit_id": head_sha})
    else:
        result = request("PUT", f"{endpoint}/reviews/{existing}", {"body": body})
    return result["id"]


def gh_request(method: str, path: str, payload: dict | None = None):
    command = ["gh", "api", path]
    if method != "GET":
        command += ["--method", method, "--input", "-"]
    result = subprocess.run(
        command, input=json.dumps(payload, ensure_ascii=False) if payload else None,
        capture_output=True, text=True, encoding="utf-8", check=True,
    )
    return json.loads(result.stdout)


if __name__ == "__main__":
    review_id = publish_review(
        Path("ai-summary.md").read_text(encoding="utf-8"),
        Path("changed-files.txt").read_text(encoding="utf-8"),
        os.environ["GH_REPO"], int(os.environ["PR_NUMBER"]),
        os.environ["EXPECTED_HEAD"], gh_request,
    )
    print(f"Published review {review_id}")
